name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Actions
        id: greeting
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Giorgio
      - name: Echo time
        run: echo "${{steps.greeting.output.time}}"  


