name: Container Deployment
on: pull_request

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:10.18.0-jessie
    steps:
      - name: Log node 
        run: node -v
      - name: Step with docker version
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: "/bin/echo"
          args: 'Hello world!'
      - name: Step with docker  version 
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: /usr/local/bin/node
          args: -v
      - uses: actions/checkout@v1
      - name: Run a script
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: ./script.sh
          args: "Hello world"
      - name: Send a slack message
        uses: docker://technosophos/slack-notify
        env: 
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK}}
          SLACK_MESSAGE: "Hello world to slack"

  node-docker:
    runs-on: ubuntu-20.04
    services:
      app:
        image: alialaa17/node-api
        ports:
          - "3001:3000"
      mongo:
        image: mongo
        ports:
          - "27017:27017"
    steps:
      - name: Post a user
        run: "curl -X POST http://localhost:3001/api/user -H 'Content-Type: application/json' -d '{\"username\": \"giorgio\", \"address\": \"gd\"}'"
      - name: Get users
        run: curl http://localhost:3001/api/users
