name: Matrix
on: push

jobs:
  log-node-version:
    runs-on: ubuntu-latest
    steps:
      - name: Log node version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: 6
      - name: Check new version
        run: node -vs